### PR TITLE
[SSHD-849] Using a ClientChannelPendingMessagesQueue to regulate messages order while forwarding channel is being set up

### PR DESCRIPTION
**Pull request by lgoldstein**

### CODE REVIEW

**Comment by lgoldstein** [comment]
The code can also be checked out and tested from https://github.com/lgoldstein/mina-sshd/tree/SSHD-849.

**Comment by fcav1973** [comment]
We have tested you modifications, but we have found some problems, I thinks related to `queue.waitForPendingMessagesFlush(TimeUnit.SECONDS, maxWaitSec);` inside `DefaultForwardingFilter` which is blocking the thread pool. We have worked out a patch for this (something like adding another feature field to `ClientChannelPendingMessagesQueue` so to append the listener executing `channel.close`) and we are trying it (with good results till now). We will give you feedback in the next few days.

**Comment by lgoldstein** [comment]
Good news - will await your input

**Comment by robertodeandrea** [comment]
Hi Lyor, 
we made definitive changes to our code that is working fine. 
Our last commits are at https://github.com/robertodeandrea/mina-sshd/commit/c381e522dc254387009d82612dc15f0c584dece6

**Comment by lgoldstein** [comment]
There are quite a few issues with this code - however, I think you are on to something with the usage of the extra future (the completion one). I have made the changes based on your idea into my original code and pushed it into the same branch (https://github.com/lgoldstein/mina-sshd/tree/SSHD-849) + PR. Can you review + test it an see ?

**Comment by fcav1973** [comment]
Hi,
your modifications seems to be good. We're still testing with previous one
since we're now trying to overcome problems with SSH_MSG_CHANNEL_WINDOW_ADJUST
management that, since it's blocking, it's forcing us to use a thread poll
equal to max level of concurrent channels.
We'll test your version of the modification in the next days and give you a
feedback.


Il giorno mar 23 ott 2018 alle ore 17:37 Lyor Goldstein <
notifications@github.com> ha scritto:

**Comment by lgoldstein** [comment]
Great - hope you can overcome the `SSH_MSG_CHANNEL_WINDOW_ADJUST` issue...

**Pull request closed without merging**
