### PR TITLE
[SSHD-393] Fix frozen ssh output stream on window adjust

### PR DESCRIPTION
**Pull request by marosmars**
When server output stream delayed write it did not resume it after the window was adjusted
Resume writes the same way client ssh channel does

maros.mars@gmail.com

### CODE REVIEW

**Comment by tonydamage** [comment]
marosmars could you also attach unit test?

**Comment by marosmars** [comment]
The unit tests are already there. I can see them within the commit

**Comment by gnodet** [comment]
Could you please close this PR now ?

**Comment by marosmars** [comment]
Done. Thx
When are you releasing new version of mina-sshd with this fix included ?

**Comment by gnodet** [comment]
Very soon, I'm mainly waiting for a confirmation that SSHD-348 is fixed.

**Pull request closed without merging**
