### PR TITLE
Update client-setup.md

### PR DESCRIPTION
**Pull request by idontusenumbers**
Fixed case in method call to setUpDefaultClient in example

### CODE REVIEW

**Review by lgoldstein — COMMENTED** [review]
While I understand the sentiment, the method is so widely used that I don't see the value of introducing this incompatibility.

**Comment by idontusenumbers** [comment]
The case in the example does not currently match the actual java code. This fixes the example so that it compiles.

**Comment by lgoldstein** [comment]
Sorry - my mistake - for some reason I misunderstood and thought you were suggesting we rename the actual method. I'll be happy to make this correction in our documentation

**Comment by lgoldstein** [comment]
Thanks for bringing this to our attention - I fixed it (there were a few more locations with wrong case). You can close the PR

**Pull request closed without merging**
