### PR TITLE
[1.1.x]question about use mina-sshd as ssh-client and send shell command

### PR DESCRIPTION
**Pull request by fengjian1993**
SshClient client = SshClient.setUpDefaultClient();
        client.start();
        ConnectFuture connect = client.connect("xx", "xx.xx.xx.xx", 22);
        if (connect.await(5000L)) {
            ClientSession session = connect.getSession();
            session.addPasswordIdentity("xx");
            session.auth().verify(5000L);
            ChannelShell channel = (ChannelShell) session.createChannel(ClientChannel.CHANNEL_SHELL);
            channel.setIn(new NoCloseInputStream(System.in));
            channel.setOut(new NoCloseOutputStream(System.out));
            channel.setErr(new NoCloseOutputStream(System.err));
            channel.open();
            System.out.println(channel.getProperties());
            channel.waitFor(Arrays.asList(ClientChannelEvent.CLOSED), 0);
            session.close(false);
            client.stop();
I have sent via console successfully. i want to ask how to sent via java command?
Thanks.

### CODE REVIEW

**Comment by lgoldstein** [comment]
This seems like a very old version of the code. Furthermore, I am not sure sure I understand what you are trying to achieve. I would recommend using the latest version after having read the extensive [README](https://github.com/apache/mina-sshd/blob/master/README.md).

BTW - in the future, I recommend to pose such questions via dev@mina.apache.org mailing list where it is more likely to be answered by the community...

**Comment by fengjian1993** [comment]
> 
> 
> This seems like a very old version of the code. Furthermore, I am not sure sure I understand what you are trying to achieve. I would recommend using the latest version after having read the extensive [README](https://github.com/apache/mina-sshd/blob/master/README.md).
> 
> BTW - in the future, I recommend to pose such questions via [dev@mina.apache.org](mailto:dev@mina.apache.org) mailing list where it is more likely to be answered by the community...

Thanks for your reply. I trying to use websocket(exchange between web and backgroud) and apach mina sshd(exchange between sshserver and background) to realize web-ssh by javacode. But i meet a question about how can i use stream to post shell command and receive returned info. Via Eclipse console, That's very clear to to post shell command and receive returned info. :)

**Comment by lgoldstein** [comment]
Here is sketch of how I would do it (assuming the latest version) - for more details see `SshClientMain` class in the project.

```java
SshClient client = SshClient.setUpDefaultClient();
client.start();
while (...keep running...) {
    try (ClientSession session = client.connect(.....).verify(...timeout...).getSession()) {
        session.addPasswordIdentity(....);   // or addKeyIdentity...
        session.auth().verify(...timeout...);

        try (ClientChannel channel = session.createShellChannel(....)) {
             channel.setIn(new NoCloseInputStream(System.in));
             channel.setOut(new NoCloseOutputStream(System.out));
             channel.setErr(new NoCloseOutputStream(System.err));
             channel.open().verify(....timeout...);
             // This causes this thread to block until shell is closed...
             channel.waitFor(EnumSet.of(ClientChannelEvent.CLOSED), 0L);
        }
    }
}
client.stop();
```

**Comment by fengjian1993** [comment]
> 
> 
> Here is sketch of how I would do it (assuming the latest version) - for more details see `SshClientMain` class in the project.
> 
> ```java
> SshClient client = SshClient.setUpDefaultClient();
> client.start();
> while (...keep running...) {
>     try (ClientSession session = client.connect(.....).verify(...timeout...).getSession()) {
>         session.addPasswordIdentity(....);   // or addKeyIdentity...
>         session.auth().verify(...timeout...);
> 
>         try (ClientChannel channel = session.createShellChannel(....)) {
>              channel.setIn(new NoCloseInputStream(System.in));
>              channel.setOut(new NoCloseOutputStream(System.out));
>              channel.setErr(new NoCloseOutputStream(System.err));
>              channel.open().verify(....timeout...);
>              // This causes this thread to block until shell is closed...
>              channel.waitFor(EnumSet.of(ClientChannelEvent.CLOSED), 0L);
>         }
>     }
> }
> client.stop();
> ```

Yeah, i have tried that.
But that is a interaction via console. I wanna send command by java code, such as inputstream and read message which returned by ssh server by output stream. Of course, i want keep channel(or session) until i close it so that i can send command and receive message constantly. :) Thanks.

**Comment by lgoldstein** [comment]
>> But that is a interaction via console. I wanna send command by java code

Then simply use your own input/output streams instead of `System.in/out/err`

**Comment by fengjian1993** [comment]
> 
> 
> > > But that is a interaction via console. I wanna send command by java code
> 
> Then simply use your own input/output streams instead of `System.in/out/err`

T.T, May i have your some examples? I am still confusion about that.

**Comment by lgoldstein** [comment]
I am not sure what kind of examples I could provide - however in the above example

* Replace `new NoCloseInputStream(System.in)/new NoCloseOutputStream(System.out)/new NoCloseOutputStream(System.err)` with some other input/output streams that you control
* Spawn relevant **threads** to read/write from them (each according to its data "direction").

I agree it is not a simple matter - especially how to coordinate the command and its result - i.e., how to issue a command and then parse **all** its output (including any errors) while using multiple threads. Way beyond the capabilities of this discussion....

**Comment by fengjian1993** [comment]
new issue about mina sshd

14:33:33.980 [NioProcessor-1] DEBUG org.apache.sshd.server.kex.ECDHP521 - Received SSH_MSG_KEXDH_INIT
14:33:34.015 [NioProcessor-1] DEBUG org.apache.sshd.server.kex.ECDHP521 - K_S:  00 00 00 07 73 73 68 2d 64 73 73 00 00 01 01 00 80 32 de 43 6b f2 c8 3b 5e 0e 74 a3 ab f6 e6 b2 77 48 86 23 6b de 17 d1 f2 b6 53 7e b0 66 1f c3 c2 bf 50 61 b1 f9 f0 fc d4 a4 f9 ab d7 8c 79 56 4d 29 ce a3 33 b0 89 ff e4 f6 4a 7f c0 f9 9a a6 5f 06 f4 88 c5 84 7c f5 ff a8 15 1b 53 6d 80 5f 27 ec 3f 19 53 5e 52 07 20 a1 a2 46 7c 3c 09 62 3c 9d e1 41 da bd 38 92 00 f7 2f a6 cb 7f 9b 3c 7c 99 3d 50 60 62 d6 64 dc 0d 42 a0 7e 78 63 a7 1b 26 2b 9f d1 5d 68 c5 81 7a 1a f4 23 be fe 79 f9 70 a1 cd 4f f9 16 e3 95 f7 ee 2c d8 2b d5 ad 88 65 a2 4b 29 0a a8 db ec 66 91 58 6f b6 75 17 79 12 74 68 89 9d 09 af 02 b9 8c 4f 99 d6 6f 65 01 64 4c a7 ed 49 6f d3 a1 b7 1d 11 f6 5a a4 0b 23 65 7b 5f a1 4d ff 55 45 0c 90 16 a1 44 97 a7 22 ed 39 71 9c 04 37 34 eb 85 19 82 61 5a 64 96 f9 47 f7 9b 51 d8 5b 9f 01 0b d3 c7 ee 66 fc 97 00 00 00 21 00 ea f9 4d c3 f1 05 48 93 d9 81 88 0f 7d f9 59 d9 f0 27 7c 03 10 e6 86 96 2b b8 63 66 34 36 31 69 00 00 01 00 5c 44 ed 09 3d 2f 1e 36 9b 1c dc 1c 7d 0c c0 ae 50 df 87 49 af 15 06 1f 61 c6 03 02 6c 78 c7 de 12 ad 3c 89 8e 6c 0a 5b 9c b8 0c 63 b9 90 9a 74 88 09 18 46 70 9d 18 6e 88 7e 84 99 2f 46 1f 1c be fc 72 3b 2d 34 9c a0 ce 63 1c b9 61 99 00 a2 2f d4 d3 47 21 b3 d4 b6 5c 32 6c c3 47 b3 66 95 4a 7f 15 26 f9 cc 30 96 e6 c7 d6 55 b1 3e b0 21 5d 53 56 fd 9b 5a 8c 75 f7 f8 eb 63 13 e4 10 2e 97 3d 54 90 8a 0b f5 81 68 2c 85 a5 bc f2 b9 97 20 fc 8f fb 0b 75 c0 f8 b2 d8 69 97 31 48 2a 83 e7 bb ea 80 d8 6b fe 90 a8 f6 4e 93 23 16 12 a8 0a bd 72 54 b4 8c 3c bd 69 6f 66 0b 0f c9 42 5c d5 10 ab aa 51 27 b1 bb 97 88 20 60 be 39 d3 57 8e 9e 20 bb 1f 64 1d 2f 72 83 13 45 68 a5 91 cc 54 2d 69 0b 97 fc a1 70 46 02 f7 76 7b d3 35 39 0c 15 8c 1d f5 d2 91 b1 1c e9 de be 3f ce 2d d0 00 00 01 00 18 c1 65 43 e1 db ea 86 15 5d 4e 03 1e fe 51 68 95 48 98 f4 55 3e ec bc 98 45 b5 a1 d6 0b 23 64 f0 14 fc fa 7b ad 5f db 74 d5 69 34 47 e8 98 3a bc 6d a5 6a c9 b1 65 cd 9b e0 e7 4f 3c 65 57 83 c6 7b d8 a2 e7 bb 7c a3 5b f0 28 01 81 44 1e 5d 6d 76 f1 17 48 3e 37 c1 af f7 15 90 29 83 b4 81 e1 9f 15 b9 22 14 1f 19 57 b7 27 a1 75 cc df 7f 3a 8b e1 4f b0 bc 9b 25 01 ec 0e 04 0b cf 34 1c ed c6 de 55 83 92 cb 35 9f 2e a1 03 b3 95 07 77 0b 65 d2 ad 22 34 22 5b 84 ff d6 32 14 d5 52 7b 1c 1d 14 ca be 00 09 89 3d 6f 7b 7e e1 46 56 f8 0b 97 1c 20 be 9a bb b2 c6 70 04 7c c0 b1 36 82 dd 99 84 91 61 7b 4b 3d c4 87 79 47 de a0 50 61 31 7d fa 85 98 fa ed c0 92 ba 72 36 c0 3e 31 04 1e ce 86 4f 59 9e 0b 26 f7 e5 6e 3a 74 18 c8 24 33 da ea 7d 36 48 cc 73 44 25 cf 1e 24 b9 17 84
14:33:34.015 [NioProcessor-1] DEBUG org.apache.sshd.server.kex.ECDHP521 - f:    04 01 4c 9a 12 d8 f1 e1 a6 63 cb 95 ac 4a ee 0a b5 38 9d ea ed b5 2c 8f 8f f1 d8 15 3f 6c 96 70 25 1d dc c1 e2 fe b9 2e 7f 5f 69 26 ed 76 47 22 c7 97 25 ca 4a 1f a7 eb 7f 9c 08 c2 0f b4 87 c5 88 08 fb 00 1a 8b 9d 59 06 3e 08 7c 33 15 90 ba a7 72 e5 7f af 59 dc e9 3f ec 24 3b b6 d6 10 18 49 9a 06 76 2d 7b 3f 7f cf e8 05 87 eb 2a 7a 4f 44 65 bd bc 01 3a 95 3e ae 82 d5 45 1a 52 e7 a0 d7 52 52 4e b7
14:33:34.015 [NioProcessor-1] DEBUG org.apache.sshd.server.kex.ECDHP521 - sigH: 00 00 00 07 73 73 68 2d 64 73 73 00 00 00 28 2b 82 a0 d4 90 98 f9 61 c3 ed c8 43 d4 8c 7a c1 65 f3 f2 96 80 fe 42 28 9d 71 bd 74 f9 51 07 c5 24 69 c0 1c c3 a2 a8 6e
14:33:34.015 [NioProcessor-1] DEBUG org.apache.sshd.server.kex.ECDHP521 - Send SSH_MSG_KEXDH_REPLY
14:33:34.015 [NioProcessor-1] DEBUG o.a.s.server.session.ServerSession - Send SSH_MSG_NEWKEYS
14:33:34.017 [NioProcessor-1] DEBUG o.a.s.server.session.ServerSession - Received SSH_MSG_DISCONNECT (reason=9, msg=The server's host key failed to verify.  This could mean that the server you are connected to is impersonating the server it claims to be. A connection could not be established. )

**Comment by fengjian1993** [comment]
@lgoldstein would you please help me to solve above question :)
It always successful before. But yeastday, i started mina sshd server on my laptop, then access it by putty, it return "Signature from server's host key is invalid". And in console, it output as:
14:48:06.521 [NioProcessor-1] DEBUG o.a.s.server.session.ServerSession - Client version string: SSH-2.0-PuTTY_Release_0.73
14:48:06.532 [NioProcessor-1] DEBUG o.a.s.server.session.ServerSession - Received SSH_MSG_KEXINIT
14:48:06.533 [NioProcessor-1] INFO  o.a.s.server.session.ServerSession - Kex: server->client aes128-ctr hmac-sha2-256 none
14:48:06.533 [NioProcessor-1] INFO  o.a.s.server.session.ServerSession - Kex: client->server aes128-ctr hmac-sha2-256 none
14:48:06.799 [NioProcessor-1] DEBUG org.apache.sshd.server.kex.ECDHP256 - Received SSH_MSG_KEXDH_INIT
14:48:06.823 [NioProcessor-1] DEBUG org.apache.sshd.server.kex.ECDHP256 - K_S:  00 00 00 07 73 73 68 2d 64 73 73 00 00 01 01 00 80 32 de 43 6b f2 c8 3b 5e 0e 74 a3 ab f6 e6 b2 77 48 86 23 6b de 17 d1 f2 b6 53 7e b0 66 1f c3 c2 bf 50 61 b1 f9 f0 fc d4 a4 f9 ab d7 8c 79 56 4d 29 ce a3 33 b0 89 ff e4 f6 4a 7f c0 f9 9a a6 5f 06 f4 88 c5 84 7c f5 ff a8 15 1b 53 6d 80 5f 27 ec 3f 19 53 5e 52 07 20 a1 a2 46 7c 3c 09 62 3c 9d e1 41 da bd 38 92 00 f7 2f a6 cb 7f 9b 3c 7c 99 3d 50 60 62 d6 64 dc 0d 42 a0 7e 78 63 a7 1b 26 2b 9f d1 5d 68 c5 81 7a 1a f4 23 be fe 79 f9 70 a1 cd 4f f9 16 e3 95 f7 ee 2c d8 2b d5 ad 88 65 a2 4b 29 0a a8 db ec 66 91 58 6f b6 75 17 79 12 74 68 89 9d 09 af 02 b9 8c 4f 99 d6 6f 65 01 64 4c a7 ed 49 6f d3 a1 b7 1d 11 f6 5a a4 0b 23 65 7b 5f a1 4d ff 55 45 0c 90 16 a1 44 97 a7 22 ed 39 71 9c 04 37 34 eb 85 19 82 61 5a 64 96 f9 47 f7 9b 51 d8 5b 9f 01 0b d3 c7 ee 66 fc 97 00 00 00 21 00 ea f9 4d c3 f1 05 48 93 d9 81 88 0f 7d f9 59 d9 f0 27 7c 03 10 e6 86 96 2b b8 63 66 34 36 31 69 00 00 01 00 5c 44 ed 09 3d 2f 1e 36 9b 1c dc 1c 7d 0c c0 ae 50 df 87 49 af 15 06 1f 61 c6 03 02 6c 78 c7 de 12 ad 3c 89 8e 6c 0a 5b 9c b8 0c 63 b9 90 9a 74 88 09 18 46 70 9d 18 6e 88 7e 84 99 2f 46 1f 1c be fc 72 3b 2d 34 9c a0 ce 63 1c b9 61 99 00 a2 2f d4 d3 47 21 b3 d4 b6 5c 32 6c c3 47 b3 66 95 4a 7f 15 26 f9 cc 30 96 e6 c7 d6 55 b1 3e b0 21 5d 53 56 fd 9b 5a 8c 75 f7 f8 eb 63 13 e4 10 2e 97 3d 54 90 8a 0b f5 81 68 2c 85 a5 bc f2 b9 97 20 fc 8f fb 0b 75 c0 f8 b2 d8 69 97 31 48 2a 83 e7 bb ea 80 d8 6b fe 90 a8 f6 4e 93 23 16 12 a8 0a bd 72 54 b4 8c 3c bd 69 6f 66 0b 0f c9 42 5c d5 10 ab aa 51 27 b1 bb 97 88 20 60 be 39 d3 57 8e 9e 20 bb 1f 64 1d 2f 72 83 13 45 68 a5 91 cc 54 2d 69 0b 97 fc a1 70 46 02 f7 76 7b d3 35 39 0c 15 8c 1d f5 d2 91 b1 1c e9 de be 3f ce 2d d0 00 00 01 00 18 c1 65 43 e1 db ea 86 15 5d 4e 03 1e fe 51 68 95 48 98 f4 55 3e ec bc 98 45 b5 a1 d6 0b 23 64 f0 14 fc fa 7b ad 5f db 74 d5 69 34 47 e8 98 3a bc 6d a5 6a c9 b1 65 cd 9b e0 e7 4f 3c 65 57 83 c6 7b d8 a2 e7 bb 7c a3 5b f0 28 01 81 44 1e 5d 6d 76 f1 17 48 3e 37 c1 af f7 15 90 29 83 b4 81 e1 9f 15 b9 22 14 1f 19 57 b7 27 a1 75 cc df 7f 3a 8b e1 4f b0 bc 9b 25 01 ec 0e 04 0b cf 34 1c ed c6 de 55 83 92 cb 35 9f 2e a1 03 b3 95 07 77 0b 65 d2 ad 22 34 22 5b 84 ff d6 32 14 d5 52 7b 1c 1d 14 ca be 00 09 89 3d 6f 7b 7e e1 46 56 f8 0b 97 1c 20 be 9a bb b2 c6 70 04 7c c0 b1 36 82 dd 99 84 91 61 7b 4b 3d c4 87 79 47 de a0 50 61 31 7d fa 85 98 fa ed c0 92 ba 72 36 c0 3e 31 04 1e ce 86 4f 59 9e 0b 26 f7 e5 6e 3a 74 18 c8 24 33 da ea 7d 36 48 cc 73 44 25 cf 1e 24 b9 17 84
14:48:06.823 [NioProcessor-1] DEBUG org.apache.sshd.server.kex.ECDHP256 - f:    04 c5 4b 90 76 95 83 6c e8 d5 18 e5 fb 2b da 66 ba 40 10 a0 aa 01 65 d4 d1 8d 4e 56 fd c2 48 a8 57 b8 74 67 64 af 70 72 93 78 a4 cc 37 0a dc 93 a6 7f 67 65 fb fd 28 f4 26 37 7a a3 c4 03 fb a7 1e
14:48:06.824 [NioProcessor-1] DEBUG org.apache.sshd.server.kex.ECDHP256 - sigH: 00 00 00 07 73 73 68 2d 64 73 73 00 00 00 28 ad e4 e2 cb 40 68 2d 79 bc 8b 2b 51 82 a3 25 42 c4 2f 63 aa 85 33 7b f4 aa f3 04 ae 09 74 80 8d 2c 1f 8e 0f e7 52 81 e4
14:48:06.824 [NioProcessor-1] DEBUG org.apache.sshd.server.kex.ECDHP256 - Send SSH_MSG_KEXDH_REPLY
14:48:06.824 [NioProcessor-1] DEBUG o.a.s.server.session.ServerSession - Send SSH_MSG_NEWKEYS
14:48:56.079 [NioProcessor-1] DEBUG o.a.s.server.session.ServerSession - Received SSH_MSG_DISCONNECT (reason=2, msg=Signature from server's host key is invalid)

I tried same code in my friend laptop, it's ok to access.
Thanks for help :)

**Comment by lgoldstein** [comment]
It seems that you are still using an old version - the problem you describe seems familiar and I am pretty sure it is an issue we fixed in subsequent releases. As far as I can remember this had to do with RSA key padding being handled incorrectly - though the details escape me since this was a long time ago...

**Comment by fengjian1993** [comment]
> 
> 
> It seems that you are still using an old version - the problem you describe seems familiar and I am pretty sure it is an issue we fixed in subsequent releases. As far as I can remember this had to do with RSA key padding being handled incorrectly - though the details escape me since this was a long time ago...

hi, i have solved this issus. ;) maybe my mina-sshd version is low, i should set key.pem created by 1024. anyway, thanks for your warmly reply!

**Comment by lgoldstein** [comment]
>>  i have solved this issue .. i should set key.pem created by 1024

I am  pretty sure this will not solve your problem (if it is what I remember) - you were just lucky to choose RSA key parameters that do not require padding - but this may change the next time you generate a new key - regardless of the key size

>> maybe my mina-sshd version is low

It is low - you should definitely upgrade...

**Pull request closed without merging**
